name: svg_to_flutter
description: A tool for converting svg files to a font. To facilitate developers to quickly generate icon font (.ttf) and Flutter icon class, We developed the svg_to_flutter library.
version: 1.0.0
repository: https://github.com/camus-design/svg_to_flutter.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.6.0
  code_builder: ^4.10.1
  dart_style: ^2.3.7
  io: ^1.0.4
  path: ^1.9.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

executables:
  svg_to_flutter: main
